### PR TITLE
angular 2 -> angular; angular 1.x -> angularjs 1.x

### PR DESCRIPTION
**Pull request by lazarljubenovic**
I've left the 1 vs 2 clarification in the first few paragraphs and then moved on to just AngularJS and Angular.

Not sure if you're ready to embrace the quest to change this in all articles, tags, etc. (Not to mention majority of people probably still Google for "Angular 2", and you can't really blame them.) If you are, however, willing to reword older articles, I'm happy to help. 

I've left the preamble untouched, along with the title because of backlinks and SEO and whatnot. If you have ideas about how to approach these, just give me a shout and I'll change it. Of course, feel free to discard this PR if you'd rather let past articles stay the same, and preach the "It's just Angular" mantra only in future articles.

### CODE REVIEW

**Comment by toddmotto** [comment]
Totally up for changing this! I think we should remove `1.x` from `AngularJS 1.x` and just keep it as `AngularJS`. In the first paragraph, I think it'd be best to do something like:

_Bla bla bla Angular (v2+) and AngularJS (1.x)..._

What do you think? :)

**Comment by lazarljubenovic** [comment]
Sure! What'd you like to do with URL, permalinks, titles and tags?

```
permalink: /transclusion-in-angular-2-with-ng-content
title: Transclusion in Angular 2 with ng-content
path: 2016-03-22-transclusion-in-angular-2-with-ng-content.md
tags:
- Angular 2
```

I can go through all articles in a single commit so all cross-refs from your blog are still correct, but what about people linking to you? I'm not familiar with jekyll concept of redirecting.

Maybe the best idea is to keep permalinks and change only titles?

**Comment by toddmotto** [comment]
We will have to leave the `permalink` as many stackoverflow/etc links will 404 otherwise. The `path` is just for "Edit on GitHub" link so not totally important. I think for now leaving Angular 2 there won't do any harm (page title) 💃

**Comment by lazarljubenovic** [comment]
Gotcha. Time to binge-read your whole blog in that case :grin: :popcorn: 

I'll submit a new PR some time this week. You can either merge this one now if you want or I'll re-apply the changes for this article in the batch PR.

**Comment by toddmotto** [comment]
Merged it! Thanks dude, really appreciate it :) and hey, honestly no need to spend so much time on my blog haha! It's a lot of work to edit them all!! :)

**Pull request merged**
